CREATE TABLE `game` (
  `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '主键',
  `icon` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '游戏图标',
  `cover` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '游戏封面',
  `name` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '游戏名称',
  `region` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '区服',
  `process` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '进程',
  `route` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '路由',
  `description` TEXT COMMENT '描述',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='游戏表';